name: .NET

on:
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
    
      - name: Build
        shell: bash
        run: |
          dotnet publish ADM/ADM.csproj -r win-x64 -c Release -o ./ -p:PublishSingleFile=true --self-contained false

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "./ADM.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
